_target_: src.datamodules.mnist_datamodule.MNISTDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [59_900, 100, 10_000]
num_workers: 0
pin_memory: False
deskew: False
fashionmnist: False
