_target_: src.models.dgn_model_new.DGNModel

input_size: 784
lin1_size: 25
lin2_size: 20
lin3_size: 1
lin4_size: 1
num_layers_used: 3

num_classes: 10
num_branches: 16
# pred_clip: 0.01
pred_clip: 1e-5
weight_clipping: 5

# lr: 0.20
lr: 5e-3
dynamic_lr: false

weight_decay: 0.0005
ctx_bias: false
base_bias: false
pretrained_ctx: false
gpu: false
svm_context: false
plot: false
train_autograd_params: false
autograd_weights: false
