_target_: src.models.dgn_model.DGNModel

input_size: 2
lin1_size: 1
lin2_size: 1
lin3_size: 1
num_classes: 3
num_branches: 5
num_layers_used: 1
pred_clipping: 0.01
weight_clipping: 5
lr: 0.01
weight_decay: 0.0005
trained_ctx: false
gpu: false
svm_context: false
plot: true
train_context: true
