_target_: src.models.gln_model.GLNModel

input_size: 2
lin1_size: 1
lin2_size: 1
lin3_size: 1
num_classes: 3
num_subcontexts: 4
pred_clipping: 0.01
weight_clipping: 5
num_layers_used: 1
lr: 0.001
weight_decay: 0.0005
gpu: false
svm_context: false
plot: true
train_autograd_params: false
