_target_: src.models.gln_model.GLNModel

input_size: 784
lin1_size: 16
lin2_size: 16
lin3_size: 1
lin4_size: 1
num_layers_used: 3

num_classes: 10
num_subcontexts: 4
pred_clip: 1e-5
# pred_clip: 0
w_clip: 5
base_bias: false
ctx_bias: true

# lr: 0.20
lr: 1e-3
dynamic_lr: false

weight_decay: 0.0005
gpu: false
svm_context: false
plot: false
# train_autograd_params: false

ctx_evol_batch: true
evol_num_ep: 10

ctx_evol_pretrain: false
ctx_evol_sample: false
# train_evol_sample: false
ctx_svm_pretrain: true
ctx_svm_pretrain_force_redo: true
