_target_: src.models.gln_model.GLNModel

input_size: 784
lin1_size: 4
lin2_size: 4
lin3_size: 1
lin4_size: 1
num_layers_used: 3

num_classes: 10
num_subcontexts: 4
# pred_clip: 0.01
pred_clip: 0
w_clip: 5

# lr: 0.20
lr: 1e-3
dynamic_lr: false

weight_decay: 0.0005
ctx_bias: true
gpu: false
svm_context: false
plot: false
train_autograd_params: false
