_target_: src.models.mnist_gln_model.MNISTGLNModel

input_size: 784
lin1_size: 10
lin2_size: 5
lin3_size: 1
num_classes: 10
num_subcontexts: 4
pred_clipping: 0.01
weight_clipping: 5
lr: 0.001
weight_decay: 0.0005
gpu: false