_target_: src.models.mnist_dgn_model.MNISTDGNModel

input_size: 784
lin1_size: 100
lin2_size: 20
lin3_size: 1
num_classes: 10
num_branches: 10
pred_clipping: 0.01
weight_clipping: 5
lr: 0.001
weight_decay: 0.0005
gpu: false